eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

okta:
  oauth2:
    issuer: https://dev-25801481.okta.com/oauth2/default
    audience: api://default
